import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import { ensureHub,hubPaths,loadConfig,saveConfig,setBind } from '../../src/core/config.ts';
import {applyBind} from '../../src/core/bind.ts';
import {adoptSkills,resolveSkillConflict,relinkHubSkills,skillRecords,skillTreeBlocked} from '../../src/core/skills.ts';
import {writeAllowed,restoreIdentity,listIdentityBackups} from '../../src/core/files.ts';
import {saveVaultFromMarkdown,setVaultGrants,loadVault,vaultEnvVars} from '../../src/core/vault.ts';
import {rebuildIndex,listSessions,visibleHubSessions,closeSessionIndex} from '../../src/core/sessions.ts';
import {writeProjectMemory} from '../../src/core/memory.ts';
import {syncMemoryInjects} from '../../src/core/deliver.ts';
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'hub-review3-'));
const put=async(p:string,v:string)=>{await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,v)};
const exists=async(p:string)=>fs.lstat(p).then(()=>true,()=>false);
let count=0,failures=0;
async function check(name:string,fn:()=>Promise<void>){closeSessionIndex();const h=path.join(temp,String(++count));process.env.HOME=h;process.env.AGENT_HUB_ROOT=path.join(h,'.agent-hub');process.env.AGENT_HUB_VAULT_KEY=randomBytes(32).toString('hex');await ensureHub();try{await fn();console.log('REPRODUCED '+name)}catch(e){failures++;console.log('NOT REPRODUCED '+name+' '+String(e))}}
try {
 await check('T01 late delivery failure strands adopted Own skill',async()=>{const h=process.env.HOME!;await put(path.join(h,'.workbuddy/skills/demo/SKILL.md'),'# demo');await put(path.join(h,'.grok/skills'),'occupied-file');await assert.rejects(()=>applyBind({agent:'workbuddy',layer:'skills',value:'hub',skillsMode:'adopt'}));assert.equal((await loadConfig()).bind.workbuddy.skills,'own');assert.equal(await exists(path.join(h,'.workbuddy/skills/demo')),false);assert.equal(await exists(path.join(hubPaths().skills,'demo/SKILL.md')),true);});
 await check('T02 adopting existing personal symlink leaves runtime on old source',async()=>{const h=process.env.HOME!;const source=path.join(h,'.agents/skills/demo');await put(path.join(source,'SKILL.md'),'# source');await fs.mkdir(path.join(h,'.workbuddy/skills'),{recursive:true});await fs.symlink(source,path.join(h,'.workbuddy/skills/demo'));const r=await applyBind({agent:'workbuddy',layer:'skills',value:'hub',skillsMode:'adopt'});assert.equal(r.config.bind.workbuddy.skills,'hub');assert.equal((r.extra as any).conflicts.length,0);assert.equal(await fs.realpath(path.join(h,'.workbuddy/skills/demo')),await fs.realpath(source));assert.equal((await skillRecords(await loadConfig())).find(s=>s.name==='demo')!.links.workbuddy,'conflict');});
 await check('T03 first import conflict cannot be resolved without preexisting Hub skill',async()=>{const h=process.env.HOME!;await put(path.join(h,'.grok/skills/demo/SKILL.md'),'# grok');await put(path.join(h,'.cursor/skills/demo/SKILL.md'),'# cursor');const r=await adoptSkills();assert.equal(r.conflicts.length,1);await assert.rejects(()=>resolveSkillConflict('demo','agent',path.join(h,'.grok/skills/demo')),/Hub 中没有/);});
 await check('T04 concurrent successful revocations lose updates or corrupt ciphertext',async()=>{await saveVaultFromMarkdown('# Vault\n\n## alpha\n密钥: fake-alpha\n\n## beta\n密钥: fake-beta\n',{alpha:['grok'],beta:['cursor']});await Promise.all([setVaultGrants('alpha',[]),setVaultGrants('beta',[])]);let v;try{v=await loadVault();}catch(e){assert.match(String(e),/authenticate|Unsupported state/);console.log('EVIDENCE T04 ciphertext authentication failed after both writes completed');return;}assert.ok(v.entries.some(e=>e.agents.length>0));console.log('EVIDENCE T04 revoked grant retained after both writes completed');});
 await check('T04b concurrent config updates lose successful changes',async()=>{await Promise.all([setBind('grok','sessions','own'),setBind('cursor','sessions','own')]);const c=await loadConfig();assert.ok(c.bind.grok.sessions!=='own'||c.bind.cursor.sessions!=='own');});
 await check('T05 subagent backups without md suffix disappear from restore list',async()=>{const h=process.env.HOME!;await put(path.join(h,'.grok/agents/helper.md'),'# original');await writeAllowed('subagent','# changed','grok','helper');const files=await fs.readdir(path.join(hubPaths().backups,'identity/grok'));assert.ok(files.some(n=>n.endsWith('.subagent.helper')));assert.equal((await listIdentityBackups('grok')).length,0);});
 await check('T06 legacy Soul backup still restores into Identity',async()=>{const h=process.env.HOME!;await put(path.join(h,'.workbuddy/IDENTITY.md'),'IDENTITY');const name='2026-09-16T01-00-00-000Z.md';await put(path.join(hubPaths().backups,'identity/workbuddy',name),'LEGACY_SOUL');await restoreIdentity('workbuddy',name);assert.equal(await fs.readFile(path.join(h,'.workbuddy/IDENTITY.md'),'utf8'),'LEGACY_SOUL');});
 await check('T07 Ctx symlink writes through into Identity',async()=>{const h=process.env.HOME!;const identity=path.join(h,'.workbuddy/IDENTITY.md');await put(identity,'IDENTITY');await fs.symlink(identity,path.join(h,'.workbuddy/USER.md'));await applyBind({agent:'workbuddy',layer:'ctx',value:'hub'});assert.match(await fs.readFile(identity,'utf8'),/hub-generated/);});
 await check('T08 indirect directory symlink bypasses protected skill tree check',async()=>{const h=process.env.HOME!;const skill=path.join(h,'.grok/skills/demo');await put(path.join(skill,'SKILL.md'),'# demo');const ext=path.join(h,'shared-assets');await fs.mkdir(ext,{recursive:true});await fs.symlink(hubPaths().vault,path.join(ext,'vault'));await fs.symlink(ext,path.join(skill,'assets'));assert.equal(await skillTreeBlocked(skill),false);await adoptSkills();assert.equal(await fs.realpath(path.join(h,'.cursor/skills/demo/assets/vault')),await fs.realpath(hubPaths().vault));});
 await check('T08b adapter mount override can write Hub links into vendor directory',async()=>{const h=process.env.HOME!;const cfg=await loadConfig();cfg.adapters={grok:{skill_dir:path.join(h,'.grok/bundled/skills')}};await saveConfig(cfg);await put(path.join(hubPaths().skills,'demo/SKILL.md'),'# demo');await relinkHubSkills();assert.equal((await fs.lstat(path.join(h,'.grok/bundled/skills/demo'))).isSymbolicLink(),true);});
 await check('T09 Chinese secret field names collide in env injection',async()=>{const env=vaultEnvVars({id:'demo',fields:[{name:'密钥',value:'KEY_VALUE',secret:true},{name:'密码',value:'PASSWORD_VALUE',secret:true},{name:'私钥',value:'PRIVATE_VALUE',secret:true}]});assert.equal(env.HUB_VAULT_DEMO_KEY,'PRIVATE_VALUE');assert.equal(Object.values(env).includes('PASSWORD_VALUE'),false);assert.equal(Object.keys(env).length,2);assert.equal(env.HUB_VAULT_DEMO,'KEY_VALUE');});
 await check('T10 post-limit filtering hides visible sessions',async()=>{const h=process.env.HOME!;for(const [agent,id,time] of [['grok','new','2026-09-16T02:00:00Z'],['hyper','old','2026-09-16T01:00:00Z']]){if(agent==='grok')await put(path.join(h,'.grok/sessions/group',id,'summary.json'),JSON.stringify({info:{id,cwd:h},generated_title:id,updated_at:time}));else{const f=path.join(h,'.grok-hyper/sessions',id+'.jsonl');await put(f,JSON.stringify({type:'session/start',id,workspace:h})+'\n');await fs.utimes(f,new Date(time),new Date(time));}}await rebuildIndex();await setBind('grok','sessions','own');const c=await loadConfig();assert.equal(visibleHubSessions(listSessions({limit:1}),c,false).length,0);assert.equal(visibleHubSessions(listSessions({limit:10}),c,false).length,1);});
 await check('T11 editing one project overrides another Agent project selection',async()=>{const h=process.env.HOME!;await fs.mkdir(path.join(h,'.grok'),{recursive:true});await fs.mkdir(path.join(h,'.cursor'),{recursive:true});await writeProjectMemory('alpha','ALPHA');await writeProjectMemory('beta','BETA');await setBind('grok','memory','hub');await syncMemoryInjects('alpha');await setBind('cursor','memory','hub');await syncMemoryInjects('beta');assert.match(await fs.readFile(path.join(h,'.grok/memory/hub-generated.md'),'utf8'),/BETA/);assert.doesNotMatch(await fs.readFile(path.join(h,'.grok/memory/hub-generated.md'),'utf8'),/ALPHA/);});
 await check('T12 client blur masking exposes custom and multiline secrets',async()=>{const app=await fs.readFile(new URL('../../web/app.js', import.meta.url),'utf8');const source=app.slice(app.indexOf('function maskNow('),app.indexOf('async function toggleVaultReveal('));const ctx=vm.createContext({});vm.runInContext(source,ctx);const masked=vm.runInContext('maskNow("## test\\n账号: CUSTOM_SECRET\\n密钥: FIRST_LINE\\nSECOND_LINE")',ctx);assert.match(masked,/CUSTOM_SECRET/);assert.match(masked,/SECOND_LINE/);assert.doesNotMatch(masked,/FIRST_LINE/);});
 await check('T13 reveal replaces unsaved Vault draft with persisted text',async()=>{const app=await fs.readFile(new URL('../../web/app.js', import.meta.url),'utf8');const source=app.slice(app.indexOf('async function toggleVaultReveal('),app.indexOf('async function scanProjectSkills('));const editor={value:'UNSAVED_DRAFT'};const button={textContent:''};const ctx=vm.createContext({vaultState:{reveal:false,dirty:true,markdown:''},$: (id:string)=>id==='#vault-editor'?editor:button,api:async()=>({markdown:'PERSISTED_TEXT'})});vm.runInContext(source,ctx);await vm.runInContext('toggleVaultReveal()',ctx);assert.equal(editor.value,'PERSISTED_TEXT');});
}finally{closeSessionIndex();await fs.rm(temp,{recursive:true,force:true})}
console.log(`SCENARIOS ${count}, NOT_REPRODUCED ${failures}`);
if(failures)process.exitCode=1;
